stages:
  - deploy

variables:
  PYTHONPATH: "R:/deploy/cube/packages"

release-lucet:
  stage: deploy
  tags: [deploy-windows]
  script:
    - C:/cube/python3/python.exe -m releaselucet --staging --pip

docgen:
  stage: docgen
  tags: [docgenyco]
  script:
    - python -m docgenyco $CI_REPOSITORY_URL /home/documentation/production/devdoc/ "Developper documentation"
