stages:
  - deploy
  - docgen

variables:
  PYTHONPATH: "R:/deploy/cube/packages"

isilon:
  stage: deploy
  tags: [deploy-windows]
  script:
    - C:/cube/python3/python.exe c:/cube/scripts/mount-r.py
    - C:/cube/python3/python.exe -m releaselucet --staging --pip --drive ISILON

stornext:
  stage: deploy
  tags: [deploy-windows]
  script:
    - C:/cube/python3/python.exe c:/cube/scripts/mount-r.py
    - C:/cube/python3/python.exe -m releaselucet --staging --pip --drive STORNEXT

lyon:
  stage: deploy
  tags: [deploy-windows]
  script:
    - C:/cube/python3/python.exe c:/cube/scripts/mount-r.py
    - C:/cube/python3/python.exe -m releaselucet --staging --pip --drive LYON

lyonbuffer:
  stage: deploy
  tags: [deploy-windows]
  script:
    - C:/cube/python3/python.exe c:/cube/scripts/mount-r.py
    - C:/cube/python3/python.exe -m releaselucet --staging --pip --drive LYONBUFFER

docgen:
  stage: docgen
  tags: [docgenyco]
  only:
    refs:
      - master
    variables:
      - $CI_PROJECT_NAMESPACE == "cube"
  script:
    - python -m docgenyco $CI_REPOSITORY_URL /home/documentation/production/devdoc/ "Developper documentation"
